substitutions:
  _IMAGE_NAME: backend # Configure this

steps:

  - # Uses the Cloud Builders Gradle image.
    name: openjdk:11-jdk-slim
    dir: /workspace/backend
    args:
      # Uncomment for projects that do not include Jib as a plugin.
      #  - --init-script=auto-jib.gradle

      # Runs the Jib build.
      # For advanced customizations, configure the plugin in the build.gradle.
      - ./gradlew
      - jib

      # Sets the target image reference to push to.
      - --image=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'