spring:
  profiles:
    active: dev

  datasource:
    hikari:
      max-lifetime: 60000 # 60 seconds before removing connection from pool


logging:
  level:
    org:
      codevscovid19:
        stayhappyathome:
          controller: debug
