spring:
  profiles:
    active: dev


jpa:
  properties:
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow

logging:
  level:
    org:
      codevscovid19:
        stayhappyathome:
          controller: debug
