spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  datasource:
    name: stayhappyathome
    username: sa
    password: password
    initialization-mode: never
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  cloud:
    gcp:
      sql:
        database-name: irrelevant
        instance-connection-name: irrelevant:in-this:profile
      photo-bucket: stay-happy-at-home-eu-prod
